<?php

return [
    ['class' => 'fa-gauge-high', 'label' => 'Gauge High'],
    ['class' => 'fa-gauge', 'label' => 'Gauge'],
    ['class' => 'fa-wifi', 'label' => 'WiFi'],
    ['class' => 'fa-shield-halved', 'label' => 'Shield'],
    ['class' => 'fa-shield', 'label' => 'Shield (solid)'],
    ['class' => 'fa-infinity', 'label' => 'Infinity'],
    ['class' => 'fa-users', 'label' => 'Users'],
    ['class' => 'fa-user', 'label' => 'User'],
    ['class' => 'fa-user-group', 'label' => 'User Group'],
    ['class' => 'fa-headset', 'label' => 'Headset'],
    ['class' => 'fa-headphones', 'label' => 'Headphones'],
    ['class' => 'fa-chart-line', 'label' => 'Chart Line'],
    ['class' => 'fa-chart-bar', 'label' => 'Chart Bar'],
    ['class' => 'fa-chart-pie', 'label' => 'Chart Pie'],
    ['class' => 'fa-chart-simple', 'label' => 'Chart Simple'],
    ['class' => 'fa-bolt', 'label' => 'Bolt'],
    ['class' => 'fa-rocket', 'label' => 'Rocket'],
    ['class' => 'fa-star', 'label' => 'Star'],
    ['class' => 'fa-medal', 'label' => 'Medal'],
    ['class' => 'fa-trophy', 'label' => 'Trophy'],
    ['class' => 'fa-thumbs-up', 'label' => 'Thumbs Up'],
    ['class' => 'fa-check', 'label' => 'Check'],
    ['class' => 'fa-xmark', 'label' => 'X Mark'],
    ['class' => 'fa-circle-xmark', 'label' => 'X Mark Circle'],
    ['class' => 'fa-circle-info', 'label' => 'Info Circle'],
    ['class' => 'fa-circle-question', 'label' => 'Question Circle'],
    ['class' => 'fa-play', 'label' => 'Play'],
    ['class' => 'fa-video', 'label' => 'Video'],
    ['class' => 'fa-youtube', 'label' => 'YouTube'],
    ['class' => 'fa-ticket', 'label' => 'Ticket'],
    ['class' => 'fa-credit-card', 'label' => 'Credit Card'],
    ['class' => 'fa-wallet', 'label' => 'Wallet'],
    ['class' => 'fa-money-bill', 'label' => 'Money Bill'],
    ['class' => 'fa-sack-dollar', 'label' => 'Sack Dollar'],
    ['class' => 'fa-percent', 'label' => 'Percent'],
    ['class' => 'fa-tag', 'label' => 'Tag'],
    ['class' => 'fa-cart-shopping', 'label' => 'Shopping Cart'],
    ['class' => 'fa-gear', 'label' => 'Gear'],
    ['class' => 'fa-sliders', 'label' => 'Sliders'],
    ['class' => 'fa-palette', 'label' => 'Palette'],
    ['class' => 'fa-database', 'label' => 'Database'],
    ['class' => 'fa-server', 'label' => 'Server'],
    ['class' => 'fa-cloud', 'label' => 'Cloud'],
    ['class' => 'fa-computer', 'label' => 'Computer'],
    ['class' => 'fa-laptop', 'label' => 'Laptop'],
    ['class' => 'fa-mobile-screen', 'label' => 'Mobile Screen'],
    ['class' => 'fa-tv', 'label' => 'TV'],
    ['class' => 'fa-router', 'label' => 'Router'],
    ['class' => 'fa-tower-cell', 'label' => 'Tower Cell'],
    ['class' => 'fa-satellite-dish', 'label' => 'Satellite Dish'],
    ['class' => 'fa-network-wired', 'label' => 'Network Wired'],
    ['class' => 'fa-ethernet', 'label' => 'Ethernet'],
    ['class' => 'fa-cable-car', 'label' => 'Cable'],
    ['class' => 'fa-plug', 'label' => 'Plug'],
    ['class' => 'fa-power-off', 'label' => 'Power Off'],
    ['class' => 'fa-battery-full', 'label' => 'Battery Full'],
    ['class' => 'fa-signal', 'label' => 'Signal'],
    ['class' => 'fa-envelope', 'label' => 'Envelope'],
    ['class' => 'fa-phone', 'label' => 'Phone'],
    ['class' => 'fa-location-dot', 'label' => 'Location Dot'],
    ['class' => 'fa-map-pin', 'label' => 'Map Pin'],
    ['class' => 'fa-clock', 'label' => 'Clock'],
    ['class' => 'fa-calendar', 'label' => 'Calendar'],
    ['class' => 'fa-globe', 'label' => 'Globe'],
    ['class' => 'fa-earth-asia', 'label' => 'Earth Asia'],
    ['class' => 'fa-house', 'label' => 'House'],
    ['class' => 'fa-building', 'label' => 'Building'],
    ['class' => 'fa-store', 'label' => 'Store'],
    ['class' => 'fa-folder', 'label' => 'Folder'],
    ['class' => 'fa-file', 'label' => 'File'],
    ['class' => 'fa-download', 'label' => 'Download'],
    ['class' => 'fa-upload', 'label' => 'Upload'],
    ['class' => 'fa-arrow-up', 'label' => 'Arrow Up'],
    ['class' => 'fa-arrow-right', 'label' => 'Arrow Right'],
    ['class' => 'fa-arrow-down', 'label' => 'Arrow Down'],
    ['class' => 'fa-arrow-trend-up', 'label' => 'Trend Up'],
    ['class' => 'fa-arrow-trend-down', 'label' => 'Trend Down'],
    ['class' => 'fa-eye', 'label' => 'Eye'],
    ['class' => 'fa-eye-slash', 'label' => 'Eye Slash'],
    ['class' => 'fa-lock', 'label' => 'Lock'],
    ['class' => 'fa-lock-open', 'label' => 'Lock Open'],
    ['class' => 'fa-key', 'label' => 'Key'],
    ['class' => 'fa-pen', 'label' => 'Pen'],
    ['class' => 'fa-pen-to-square', 'label' => 'Edit'],
    ['class' => 'fa-trash-can', 'label' => 'Trash'],
    ['class' => 'fa-plus', 'label' => 'Plus'],
    ['class' => 'fa-minus', 'label' => 'Minus'],
    ['class' => 'fa-magnifying-glass', 'label' => 'Search'],
    ['class' => 'fa-filter', 'label' => 'Filter'],
    ['class' => 'fa-print', 'label' => 'Print'],
    ['class' => 'fa-share-nodes', 'label' => 'Share'],
    ['class' => 'fa-link', 'label' => 'Link'],
    ['class' => 'fa-copy', 'label' => 'Copy'],
    ['class' => 'fa-bars', 'label' => 'Bars / Menu'],
    ['class' => 'fa-ellipsis-vertical', 'label' => 'More Vertical'],
    ['class' => 'fa-ellipsis', 'label' => 'More Horizontal'],
    ['class' => 'fa-x', 'label' => 'Close'],
    ['class' => 'fa-chevron-right', 'label' => 'Chevron Right'],
    ['class' => 'fa-chevron-down', 'label' => 'Chevron Down'],
    ['class' => 'fa-angle-right', 'label' => 'Angle Right'],
    ['class' => 'fa-lightbulb', 'label' => 'Lightbulb'],
    ['class' => 'fa-heart', 'label' => 'Heart'],
    ['class' => 'fa-handshake', 'label' => 'Handshake'],
    ['class' => 'fa-award', 'label' => 'Award'],
    ['class' => 'fa-gem', 'label' => 'Gem'],
    ['class' => 'fa-crown', 'label' => 'Crown'],
    ['class' => 'fa-fire', 'label' => 'Fire'],
    ['class' => 'fa-face-smile', 'label' => 'Smile'],
    ['class' => 'fa-circle-exclamation', 'label' => 'Exclamation Circle'],
    ['class' => 'fa-triangle-exclamation', 'label' => 'Warning'],
    ['class' => 'fa-bell', 'label' => 'Bell'],
    ['class' => 'fa-megaphone', 'label' => 'Megaphone'],
    ['class' => 'fa-bullhorn', 'label' => 'Bullhorn'],
    ['class' => 'fa-newspaper', 'label' => 'Newspaper'],
    ['class' => 'fa-book', 'label' => 'Book'],
    ['class' => 'fa-book-open', 'label' => 'Book Open'],
    ['class' => 'fa-graduation-cap', 'label' => 'Graduation Cap'],
    ['class' => 'fa-code', 'label' => 'Code'],
    ['class' => 'fa-terminal', 'label' => 'Terminal'],
    ['class' => 'fa-cube', 'label' => 'Cube'],
    ['class' => 'fa-cubes', 'label' => 'Cubes'],
    ['class' => 'fa-layer-group', 'label' => 'Layers'],
    ['class' => 'fa-puzzle-piece', 'label' => 'Puzzle Piece'],
    ['class' => 'fa-microchip', 'label' => 'Microchip'],
    ['class' => 'fa-memory', 'label' => 'Memory'],
    ['class' => 'fa-sd-card', 'label' => 'SD Card'],
    ['class' => 'fa-hard-drive', 'label' => 'Hard Drive'],
];
